version: '3.1'
services:
  stats-server:
    build: stats-server/statistic-service
    image: ewm-stats-server-image
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-postgres-db
    environment:
      - EWM_SERVICE_URL=http://ewm-service:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-postgres-db:5432/stats-postgres

  stats-postgres-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: db_postgres_stats
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot


  ewm-service:
    build: ewm-service
    image: ewm-service-image
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-postgres-db
    environment:
      - STATISTIC_SERVICE_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-postgres-db:5432/ewm-postgres

  ewm-postgres-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: db_postgres_ewm
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot